source :rubygems
source "http://gems.rubyforge.org"
source "http://gems.github.com"
gem "MINT-statemachine" #,  :path => ".."+File::SEPARATOR+"statemachine"
gem "MINT-core",:path => ".."+File::SEPARATOR+"MINT-core"
gem "rspec", "1.3.1"
gem "dm-core","0.10.2"
gem "dm-rinda-adapter" ,  :path => ".."+File::SEPARATOR+"dm-rinda-adapter"
gem "cassowary","1.0.0"
gem "rails", "2.3.12"
gem "juggernaut", "2.0.0"
gem "em-websocket", "0.1.3"
gem "eventmachine", "0.12.10"
gem "rake","0.9.2"
gem "activesupport","2.3.12"
gem "rmagick","2.12.2"
gem "json","1.5.1"
gem "addressable","2.2.4"
gem "mongrel","1.1.5"
gem "rack","1.1.2"
gem "rdoc"
gem "i18n"

# MoBe2011 dependencies
gem "fastercsv", "1.5.4"
